schema_version: 20180708
name: fn-oradb-app-read-func
version: 0.0.1
runtime: java
build_image: oracle_jdbc_driver_docker
run_image: fnproject/fn-java-fdk:jdk9-1.0.63
cmd: io.fnproject.example.GetEmployeeFunction::handle
format: http
triggers:
- name: fn-oradb-app-read-func
  type: http
  source: /fn-oradb-app-read-func
