schema_version: 20180708
name: fn-kafka-app-send-func
version: 0.0.1
runtime: java
build_image: fn-kafka-docker
run_image: fnproject/fn-java-fdk:jdk9-1.0.63
cmd: fnkafka.example.SendEmployeeFunction::handle
format: http
timeout: 200
triggers:
- name: fn-kafka-app-send-func
  type: http
  source: /fn-kafka-app-send-func
